[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

# Test settings
fuzz_runs = 1000
verbosity = 4

# Gas settings
gas_reports = ["*"]
gas_limit = 9223372036854775807

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
